package com.centralmountaincreditunionloanamortizationapp.main;

import com.centralmountaincreditunionloanamortizationapp.models.Amortization;
import java.io.File;
import java.io.IOException;
import java.io.PrintWriter;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 * This GUI program displays a form that allows the user to enter loan details
 * (amount, annual interest rate, and loan term). It calculates the loan
 * amortization schedule and allows the user to choose where to save the report
 * using a Save File dialog. The user can generate multiple reports as desired.
 */
public class LoanReportGUI extends javax.swing.JFrame {
// Class-level variables to store loan data

    private double loanAmount;
    private double interestRate;
    private int loanYears;
    private Amortization amortization;

    /**
     * Creates new form LoanReportGUI
     */
    public LoanReportGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaReport = new javax.swing.JTextArea();
        jTextFieldAnnualInterestRate = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuFile = new javax.swing.JMenu();
        jMenuItemFileSaveAs = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItemFileClear = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItemFileExit = new javax.swing.JMenuItem();
        jMenuReport = new javax.swing.JMenu();
        jMenuItemReportData = new javax.swing.JMenuItem();
        jMenuItemReportDisplay = new javax.swing.JMenuItem();
        jMenuHelp = new javax.swing.JMenu();
        jMenuItemHelpAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Central Mountain Credit Union - Loan Amortization");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Interest and Principal Payments"));

        jTextAreaReport.setEditable(false);
        jTextAreaReport.setColumns(20);
        jTextAreaReport.setFont(new java.awt.Font("Monospaced", 0, 11)); // NOI18N
        jTextAreaReport.setRows(5);
        jScrollPane1.setViewportView(jTextAreaReport);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 484, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTextFieldAnnualInterestRate.setEditable(false);

        jLabel4.setText("Annual Interest Rate:");

        jMenuFile.setMnemonic('f');
        jMenuFile.setText("File");

        jMenuItemFileSaveAs.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItemFileSaveAs.setMnemonic('s');
        jMenuItemFileSaveAs.setText("Save As...");
        jMenuItemFileSaveAs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemFileSaveAsActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemFileSaveAs);
        jMenuFile.add(jSeparator1);

        jMenuItemFileClear.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItemFileClear.setMnemonic('l');
        jMenuItemFileClear.setText("Clear Loan Figures");
        jMenuItemFileClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemFileClearActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemFileClear);
        jMenuFile.add(jSeparator2);

        jMenuItemFileExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItemFileExit.setMnemonic('x');
        jMenuItemFileExit.setText("Exit");
        jMenuItemFileExit.setToolTipText("");
        jMenuItemFileExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemFileExitActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemFileExit);

        jMenuBar1.add(jMenuFile);

        jMenuReport.setText("Report");

        jMenuItemReportData.setMnemonic('e');
        jMenuItemReportData.setText("Enter Loan Information");
        jMenuItemReportData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemReportDataActionPerformed(evt);
            }
        });
        jMenuReport.add(jMenuItemReportData);

        jMenuItemReportDisplay.setMnemonic('d');
        jMenuItemReportDisplay.setText("Display Loan Amortization Report");
        jMenuItemReportDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemReportDisplayActionPerformed(evt);
            }
        });
        jMenuReport.add(jMenuItemReportDisplay);

        jMenuBar1.add(jMenuReport);

        jMenuHelp.setMnemonic('h');
        jMenuHelp.setText("Help");

        jMenuItemHelpAbout.setMnemonic('a');
        jMenuItemHelpAbout.setText("About");
        jMenuItemHelpAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemHelpAboutActionPerformed(evt);
            }
        });
        jMenuHelp.add(jMenuItemHelpAbout);

        jMenuBar1.add(jMenuHelp);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 342, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldAnnualInterestRate, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldAnnualInterestRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemFileSaveAsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemFileSaveAsActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Save Report");
        fileChooser.setFileFilter(new FileNameExtensionFilter("Text Documents (*.txt)", "txt"));
        fileChooser.setSelectedFile(new File("LoanAmortization.txt")); // prepopulate filename

        int userSelection = fileChooser.showSaveDialog(this);

        if (userSelection == JFileChooser.APPROVE_OPTION) {
            File fileToSave = fileChooser.getSelectedFile();

            // Ensure .txt extension
            if (!fileToSave.getName().toLowerCase().endsWith(".txt")) {
                fileToSave = new File(fileToSave.getAbsolutePath() + ".txt");
            }

            // Confirm overwrite if file exists
            if (fileToSave.exists()) {
                int response = JOptionPane.showConfirmDialog(this,
                        "The file " + fileToSave.getName() + " already exists.\nDo you want to replace it?",
                        "Overwrite File",
                        JOptionPane.YES_NO_OPTION,
                        JOptionPane.WARNING_MESSAGE);

                if (response != JOptionPane.YES_OPTION) {
                    return; // User canceled overwrite
                }
            }

            // Save file using PrintWriter
            try {
                PrintWriter out = new PrintWriter(fileToSave);
                out.println(jTextAreaReport.getText());  // save content
                out.close();

                JOptionPane.showMessageDialog(this, "Report saved successfully!");
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(this,
                        "Error saving file:\n" + ex.getMessage(),
                        "File Save Error",
                        JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jMenuItemFileSaveAsActionPerformed

    private void jMenuItemFileExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemFileExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItemFileExitActionPerformed

    private void jMenuItemReportDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemReportDataActionPerformed
        String input;

        // Get the loan amount
        input = JOptionPane.showInputDialog(this, "Enter the loan amount:");
        if (input == null) {
            return; // User cancelled
        }
        loanAmount = Double.parseDouble(input);

        // Validate the loan amount (must be non-negative)
        while (loanAmount < 0) {
            input = JOptionPane.showInputDialog(this, "Invalid amount. Enter the loan amount:");
            if (input == null) {
                return; // User cancelled
            }
            loanAmount = Double.parseDouble(input);
        }

        // Get the annual interest rate
        input = JOptionPane.showInputDialog(this, "Enter the annual interest rate:");
        if (input == null) {
            return; // User cancelled
        }
        interestRate = Double.parseDouble(input);

        // Validate the interest rate (must be non-negative)
        while (interestRate < 0) {
            input = JOptionPane.showInputDialog(this, "Invalid amount. Enter the annual interest rate:");
            if (input == null) {
                return; // User cancelled
            }
            interestRate = Double.parseDouble(input);
        }

        // Get the years of the loan
        input = JOptionPane.showInputDialog(this, "Enter the years of the loan:");
        if (input == null) {
            return; // User cancelled
        }
        loanYears = Integer.parseInt(input);

        // Validate the number of years (must be non-negative)
        while (loanYears < 0) {
            input = JOptionPane.showInputDialog(this, "Invalid amount. Enter the years of the loan:");
            if (input == null) {
                return; // User cancelled
            }
            loanYears = Integer.parseInt(input);
        }

        // Create and initialize an Amortization object
        amortization = new Amortization(loanAmount, interestRate, loanYears);

        // Clear the report text area
        jTextAreaReport.setText("");
    }//GEN-LAST:event_jMenuItemReportDataActionPerformed

    private void jMenuItemReportDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemReportDisplayActionPerformed
        if (amortization == null) {
            JOptionPane.showMessageDialog(this,
                    "Please enter loan data first!",
                    "No Data", JOptionPane.WARNING_MESSAGE);
        } else {
            // Generate report using stored data
            String report = amortization.generateReport();

            // Display in JTextArea
            jTextAreaReport.setText(report);

            // Display annual interest rate
            jTextFieldAnnualInterestRate.setText(
                    String.valueOf(amortization.getInterestRate()));
        }
    }//GEN-LAST:event_jMenuItemReportDisplayActionPerformed

    private void jMenuItemHelpAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemHelpAboutActionPerformed
        JOptionPane.showMessageDialog(this,
                "Displays a Loan Amortization report for the Central Mountain Credit Union (CMCU).",
                "Central Mountain Credit Union - Loan Reporting System",
                JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jMenuItemHelpAboutActionPerformed

    private void jMenuItemFileClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemFileClearActionPerformed
        if (amortization != null) {
            amortization.clearData();
        }
        loanAmount = 0.0;
        interestRate = 0.0;
        loanYears = 0;
        jTextAreaReport.setText("");
        jTextFieldAnnualInterestRate.setText("");
    }//GEN-LAST:event_jMenuItemFileClearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoanReportGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoanReportGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoanReportGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoanReportGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoanReportGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuFile;
    private javax.swing.JMenu jMenuHelp;
    private javax.swing.JMenuItem jMenuItemFileClear;
    private javax.swing.JMenuItem jMenuItemFileExit;
    private javax.swing.JMenuItem jMenuItemFileSaveAs;
    private javax.swing.JMenuItem jMenuItemHelpAbout;
    private javax.swing.JMenuItem jMenuItemReportData;
    private javax.swing.JMenuItem jMenuItemReportDisplay;
    private javax.swing.JMenu jMenuReport;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JTextArea jTextAreaReport;
    private javax.swing.JTextField jTextFieldAnnualInterestRate;
    // End of variables declaration//GEN-END:variables
}
